### ISSUE TITLE
Suggestion: scrollbar-thumb-border

### ISSUE THREAD

**Issue by fabiogiolito** [adoxography/tailwind-scrollbar#100]
```
scrollbar-thumb-border-*
```

Eg: `scrollbar-thumb-border-4`
Adds a 4px border to the scrollbar-thumb. By default same color as track background.

``` css
::scrollbar-track {
  background: var(--scrollbar-track-color);
}
::scrollbar-thumb {
  border: 
    var(--scrollbar-thumb-border-width, 0px) solid 
    var(--scrollbar-thumb-border-color, var(--scrollbar-track-color, initial));
}
```

Could also add support for changing the border color just for the sake of completeness.
Eg: `scrollbar-thumb-border-red-500`
