### ISSUE TITLE
scrollbar-hover and scrollbar-active don't work on global element

### ISSUE THREAD

**Issue by micobarac** [adoxography/tailwind-scrollbar#113]
**In version 4:** (_**NOT WORKING**_)

```css
:root {
  @apply scrollbar-thumb-slate-800 scrollbar-track-slate-800/10 scrollbar-hover:scrollbar-thumb-sky-600;
}
```

```css
.ant-layout {
  @apply bg-primary-50/50 flex-row;

  .ant-layout {
    @apply scrollbar h-screen flex-col overflow-y-auto;
  }
}
```

`In version 3:` (_**WORKING**_)

```css
:root {
  @apply scrollbar-thumb-slate-800 scrollbar-track-slate-800/10 hover:scrollbar-thumb-slate-600;
}
```

```css
.ant-layout {
  @apply bg-primary-50/50 flex-row;

  .ant-layout {
    @apply scrollbar h-screen flex-col overflow-y-auto;
  }
}
```

**Comment by adoxography** [comment]
Ah, yeah, I guess I missed that one. Thanks for letting me know!

It's not just the global element - the underlying issue here is that scrollbar colour properties within variants aren't able to be inherited anymore. I used to be able to do some `postcss` hackery to effectively rewrite the CSS that was generated by `hover:scrollbar-...`; before, it looked like this, where a special custom property was set instead of being scoped inside a pseudoclass:

```css
/* scrollbar-thumb-[#000] */
:root {
    --scrollbar-thumb: #000;  /* This can be inherited */
}

/* hover:scrollbar-thumb-[#000] */
:root {
    --scrollbar-thumb-hover: #000;  /* This can be inherited too */
}
```

But now, there's really no way to do that - so you get a more predictable, but less flexible, output, where scoping prevents the property from leaking out into its children:

```css
/* scrollbar-hover:scrollbar-thumb-[#000] */
:root::-webkit-scrollbar-thumb:hover {
    --scrollbar-color: #000;  /* This can't be inherited :( */
}
```

I'll mess around with it a little more, but I suspect this feature will need to move into the tailwind configuration flie; something like this (final property names TBD):

```css
@theme {
    --scrollbar-thumb-default: ...;
    --scrollbar-thumb-hover-default: ...;
    --scrollbar-thumb-active-default: ...;
    --scrollbar-track-default: ...;
    --scrollbar-track-hover-default: ...;
    --scrollbar-track-active-default: ...;
    --scrollbar-corner-default: ...;
    --scrollbar-corrner-hover-default: ...;
}
```
