### ISSUE TITLE
The order of generated css for `hover` and `disabled` state reversed

### ISSUE THREAD

**Issue by fer-ri** [adoxography/tailwind-scrollbar#71]
Hi

with this plugin being active, then the generated css becomes reversed between `hover` and `disabled` state.  That mean, ` disabled:bg-gray-200` does not work as expected, to fix it we must use the important mark ` disabled:!bg-gray-200`

```html
<button class=" bg-indigo-500 hover:bg-indigo-600  disabled:bg-gray-200" disabled>My Button</button>
```

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {},
  },
  plugins: [
    require('tailwind-scrollbar'),
  ],
}
```

```css
.disabled\:bg-gray-200:disabled {
  --tw-bg-opacity: 1;
  background-color: rgb(229 231 235 / var(--tw-bg-opacity));
}

.hover\:bg-indigo-600:hover {
  --tw-bg-opacity: 1;
  background-color: rgb(79 70 229 / var(--tw-bg-opacity));
}
```

The normal generated css should be like this 

```css
.hover\:bg-indigo-600:hover {
  --tw-bg-opacity: 1;
  background-color: rgb(79 70 229 / var(--tw-bg-opacity));
}

.disabled\:bg-gray-200:disabled {
  --tw-bg-opacity: 1;
  background-color: rgb(229 231 235 / var(--tw-bg-opacity));
}
```

Thanks
