### ISSUE TITLE
✨ Feature request: Gradients

### ISSUE THREAD

**Issue by buhodev** [adoxography/tailwind-scrollbar#88]
Hi, thanks for your work on this plugin! I wonder if it's possible to have this utility `scrollbar-thumb-gradient-*` in order to add gradients to the scrollbar thumb:

```html
<div class="h-32 overflow-y-scroll from-red-500 to-blue-500 scrollbar scrollbar-thumb-gradient-to-br scrollbar-track-slate-300 scrollbar-track-rounded-full scrollbar-thumb-rounded-full">
  <div class="h-64 bg-slate-400"></div>
</div>
```

The snippet for it to work in vanilla css would be something like:

```css

*::-webkit-scrollbar-thumb {
  --tw-gradient-from: #ef4444 var(--tw-gradient-from-position);
  --tw-gradient-to: #3b82f6 var(--tw-gradient-to-position);
  --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to);
  background-image: linear-gradient(to bottom right, var(--tw-gradient-stops));
}
```
