### ISSUE TITLE
[bug?] "scrollbar-thin" utility doesn't work, displays default scrollbar instead

### ISSUE THREAD

**Issue by loremus** [adoxography/tailwind-scrollbar#97]
The base **scrollbar** works as intended:

```html
<div
  class="scrollbar scrollbar-thumb-rounded-full scrollbar-thumb-primary-500 flex h-full flex-col-reverse overflow-y-scroll"
  ref="scrollableLog"
>
``` 

![image](https://github.com/adoxography/tailwind-scrollbar/assets/68288461/bae68165-ed43-4350-8a3d-433cbfe6b95f)

The moment I switch to the **scrollbar-thin**, it displays the default (yet somewhat narrow) scrollbar:

```html
<div
  class="scrollbar-thin scrollbar-thumb-rounded-full scrollbar-thumb-primary-500 flex h-full flex-col-reverse overflow-y-scroll"
  ref="scrollableLog"
>
``` 

![image](https://github.com/adoxography/tailwind-scrollbar/assets/68288461/b779309b-528f-4eb0-9168-ba51e35d7edb)

Running Edge 125.0.2535.79.

**Comment by adoxography** [comment]
I can't reproduce this at all, running the same version of Edge. By any chance, are you switching `scrollbar` to `scrollbar-thin` outside of the Tailwind compiler's awareness (e.g. via the inspector)? In my experience, that's usually the culprit when it seems like utilities appear to not be working: the compiler's not aware of them, so it doesn't include them in the generated CSS.

**Comment by loremus** [comment]
@adoxography thank you for your reply. I guess I should have mentioned that all examples from the documentation site work as intended, including the thin bars, so it's not a browser's incompatibility issue.

I do realize that this issue is difficult to reproduce, given that one probably has to know the full structure of my project to do so consistently. I use several extensions in my VSCode, like Tailwind CSS Autocomplete and Tailwind CSS IntelliSense, as well as automatic Tailwind class sorting plugin for Prettier, could they be the cause? Or maybe it can be somehow influenced by the fact that I use DaisyUI theme's custom colors for it?

The `scrollbar` and `scrollbar-thin` classes are switched from the code editor, and then the whole application is rebuild each time before observing the results.

Could you recommend a particular approach to narrowing down the cause or to overall debugging of this issue (for example, checking specific styles with DevTools, etc.)?

I have additionally discovered that `active:` state for the scrollbar doesn't work for me as well (in my application, it works just fine on the documentation site), the bar's style doesn't respond to state changes like being clicked.

For example this element:

```html
<div
  class="collapse-content z-10 mr-2 max-h-80 overflow-y-scroll pr-2 scrollbar-thin scrollbar-track-primary-600 scrollbar-thumb- 
 primary-500 scrollbar-thumb-rounded-full active:scrollbar-thumb-primary-400"
>
```

Will have the following appearance, and won't respond to state changes:

![image](https://github.com/adoxography/tailwind-scrollbar/assets/68288461/17f2b6d5-a66f-44d2-bc1c-c89a7f214b4e)

**Comment by mrcaidev** [comment]
Having the same issue on Microsoft Edge Version 125.0.2535.92 (Official build) (64-bit)

**Comment by adoxography** [comment]
If anyone has an example repo that reproduces the issue, I'm happy to take a look.

> I use several extensions in my VSCode, like Tailwind CSS Autocomplete and Tailwind CSS IntelliSense, as well as automatic Tailwind class sorting plugin for Prettier, could they be the cause? Or maybe it can be somehow influenced by the fact that I use DaisyUI theme's custom colors for it?

Autocomplete, intellisense, and prettier plugins shouldn't cause any issues since they don't impact the actual Tailwind compilation. DaisyUI's a possibility, but I don't have much experience with it so I can't say for sure. I'd be surprised if that were the case, though, since you are getting colours coming through with the `scrollbar` utility.

> I have additionally discovered that `active:` state for the scrollbar doesn't work for me as well (in my application, it works just fine on the documentation site), the bar's style doesn't respond to state changes like being clicked.

That's expected if the pseudoelement styling isn't getting applied, because if there's no pseudoelement, there's nothing to get an active state. The default scrollbar in Chromium-based browsers doesn't have a lot of customizability, and custom active states are not part of its spec.

> Could you recommend a particular approach to narrowing down the cause or to overall debugging of this issue (for example, checking specific styles with DevTools, etc.)?

Here are the relevant styles you should expect to see on an element that has `scrollbar-thin scrollbar-thumb-primary-500 active:scrollbar-thumb-primary-400`, assuming you've configured your `preferredStrategy` to `pseudoelements` in your `tailwind.config.js` (which it looks like you have).

```css
/**
 * Odds are good that if a utility is misbehaving, it's one of these first two. I'd guess the first one.
 */
.scrollbar-thin::-webkit-scrollbar {
    display: block;
    width: 8px;
    height: 8px;
}

.scrollbar-thin::-webkit-scrollbar-thumb {
    background-color: var(--scrollbar-thumb);
    border-radius: var(--scrollbar-thumb-radius);
}

/**
 * This one is tricky to get to show up in Edge because it's being applied against a pseudoselector of a
 * pseudoelement; clicking on the scrollbar should get the styles to apply but they won't appear in the
 * inspector, while toggling the `:active` state in the inspector will get the styles to appear but not apply.
 * Zany, but that's just how Edge works.
 * 
 * Either way, though, I doubt this guy is at fault since you're seeing issues even before the active state
 * is applied.
 */
.scrollbar-thin::-webkit-scrollbar-thumb-active:active {
    background-color: var(--scrollbar-thumb-active, var(--scrollbar-thumb-hover, var(--scrollbar-thumb)));
}

/**
 * For the sake of completeness, this is where the colours are coming from - but since they're being
 * applied correctly against the `scrollbar` utility, I don't think there will be anything wrong with them.
 */
.scrollbar-thumb-primary-500 {
    --scrollbar-thumb: {{the-value-for-primary-500}} !important;
}

.active\:scrollbar-thumb-primary-400 {
    --scrollbar-thumb-active: {{the-value-for-primary-400}} !important;
}
```

**Comment by adoxography** [comment]
Ah, I think I might've tracked it down. It is a DaisyUI thing. In their [base styles](https://github.com/saadeghi/daisyui/blob/50646ef6c4a9879ce32661ce4d7e99f660b3076f/src/base/general.css#L4), they inject this:

```css
* {
  scrollbar-color: currentColor transparent;
}
```

When Edge (and Chrome, for that matter) sees `scrollbar-color` set, it takes that as a cue to render native scrollbars, actively blocking `::-webkit-scrollbar` pseudoelements. You can try injecting this into your CSS file, after `@tailwind base;`, to undo that setting:

```css
* {
  scrollbar-color: revert;
}
```

If this is the issue, though, I honestly don't know how you would have gotten regular old `scrollbar` styling to show up at all.
